### PR TITLE
Update global.css to have dark and light themes

### PR DESCRIPTION
**Pull request by Fenimoure**
Existing colors have been changed according to [ADW-1 Window colors](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/named-colors.html#window-colors).

### CODE REVIEW

**Comment by Fenimoure** [comment]
In case colours are defined in-line somewhere else, please, inform me about that.

**Comment by zebreus** [comment]
Thanks for the PR. I think the colors are also set in styled jsx somewhere in the `.tsx` files, for example in [overveiwWallpaper.tsx:80](https://github.com/zebreus/all-gnome-backgrounds/blob/c7e3fd63aa7ae7e594e8a9da25014a3da6b0c6a1/src/components/overviewWallpaper.tsx#L80). Searching for `color` should probably find all places where colors are set.

**Comment by Fenimoure** [comment]
Well, I'll have to complete this later then, because, as of now, I am not quite familiar with your project or with typescript as well to be honest.

**Comment by zebreus** [comment]
Ok, I looked through the code and the definition in global.css should now be the only color definitions. It seems like everything works with dark and lightmode in Chrome.

**Pull request merged**
